[package]
name = "lumberdaq"
version = "0.1.0"
edition = "2021"
description = "Data acquisition library and CLI for logging from multiple devices at once"
license = "MIT"
repository = "https://github.com/willhunt/lumberjack"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
csv = "1.3.1"
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serialport = { version = "4.5.0", features = ["serde"] }
ndarray = "0.16.1"
regex = "1.13.1"
thiserror = "2.0.20"
picolog = { path = "../picolog", features = ["serde"] }
nidaqmx = { path = "../nidaqmx" }
rusqlite = { version = "0.40.2", features = ["bundled"] }
ctrlc = "3.5.2"
evalexpr = "13.1.0"

[lib]
name = "lumberdaq"
